version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run
    desc: "Run linters on the codebase"
    silent: true

  format:
    cmds:
      - golangci-lint fmt
    desc: "Format the codebase"
    silent: true

  test:
    cmds:
      - go test -race -covermode=atomic -coverprofile=coverage.out ./...
    desc: "Run tests"
    silent: true