version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run
    desc: "Run linters on the codebase"
    silent: true

  format:
    cmds:
      - golangci-lint fmt
    desc: "Format the codebase"
    silent: true

  test:
    cmds:
      - go test -race -ldflags "-X github.com/dmitriy-rs/rollercoaster/internal/logger.MODE=TEST" -covermode=atomic -coverprofile=coverage.out ./...
    desc: "Run tests"
    silent: true

  build-dev:
    cmds:
      - go build -o rollercoaster -ldflags "-X github.com/dmitriy-rs/rollercoaster/internal/logger.MODE=DEV" ./main.go
    desc: "Build the binary"
    silent: true

  build:
    cmds:
      - go build -o rollercoaster ./main.go 
    desc: "Build the binary for production"
    silent: true

  install:
    cmds:
      - go install -ldflags "-X github.com/dmitriy-rs/rollercoaster/internal/logger.MODE=DEV"
    desc: "Install the binary"
    silent: true